/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
    "*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "#141313", // Stitch override
        foreground: "#e5e2e1", // Stitch override
        
        // --- Stitch Design System Colors ---
        "on-primary-fixed": "#07006c",
        "secondary": "#bec6e0",
        "on-primary": "#1000a9",
        "primary-fixed-dim": "#c0c1ff",
        "on-secondary-fixed": "#131b2e",
        "surface-container-high": "#2a2a2a",
        "tertiary-container": "#d97721",
        "error-container": "#93000a",
        "surface-container-highest": "#353434",
        "surface-variant": "#353434",
        "outline": "#908fa0",
        "primary-container": "#8083ff",
        "on-error": "#690005",
        "error": "#ffb4ab",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#ffdcc5",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed": "#301400",
        "tertiary-fixed-dim": "#ffb783",
        "on-surface-variant": "#c7c4d7",
        "secondary-fixed": "#dae2fd",
        "outline-variant": "#464554",
        "secondary-container": "#3f465c",
        "surface-container-low": "#1c1b1b",
        "on-primary-container": "#0d0096",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed-variant": "#3f465c",
        "on-tertiary-container": "#452000",
        "on-secondary-container": "#adb4ce",
        "on-tertiary-fixed-variant": "#703700",
        "secondary-fixed-dim": "#bec6e0",
        "on-error-container": "#ffdad6",
        "surface-container": "#201f1f",
        "surface-dim": "#141313",
        "inverse-primary": "#494bd6",
        "inverse-on-surface": "#313030",
        "surface-tint": "#c0c1ff",
        "surface": "#141313",
        "primary-fixed": "#e1e0ff",
        "on-background": "#e5e2e1",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary": "#ffb783",
        "surface-bright": "#3a3939",
        "on-tertiary": "#4f2500",
        "on-secondary": "#283044",
        // -----------------------------------

      },
      borderRadius: {
        lg: "0.5rem",
        md: "calc(var(--radius) - 2px)",
        sm: "0.25rem",
        xl: "0.75rem",
        full: "9999px",
        DEFAULT: "0.25rem"
      },
      spacing: {
        unit: "4px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
        gutter: "20px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "display-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "mono-data": ["JetBrains Mono"],
        "mono-label": ["JetBrains Mono"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "mono-data": ["13px", { lineHeight: "18px", letterSpacing: "0em", fontWeight: "400" }],
        "mono-label": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-out": {
          "0%": { opacity: "1" },
          "100%": { opacity: "0" },
        },
        "slide-up": {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "slide-down": {
          "0%": { transform: "translateY(-10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        "scale-in": {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "fade-out": "fade-out 0.2s ease-in",
        "slide-up": "slide-up 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "slide-down": "slide-down 0.4s cubic-bezier(0.16, 1, 0.3, 1)",
        "scale-in": "scale-in 0.3s cubic-bezier(0.16, 1, 0.3, 1)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}
